### ISSUE TITLE
command line args?

### ISSUE THREAD

**Issue by llogiq** [rust-crates/ergo_std#1]
I'm not sure if this is the right place, but we should include a library to simplify command line parsing. I personally like structopt, others may prefer clap or docopt.

**Comment by vitiral** [comment]
So this is a very important question of "what is ergo". I think @killercup and I have come to a resolution.

Basically the answer (currently) is: use `structopt` through `quicli`. See https://github.com/killercup/quicli/issues/43

**Comment by llogiq** [comment]
Great!
